name: IPFS Preview Deploy
on:
  push:
    branches:
      - develop
      - feature/v1
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ipfs-preview-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Inject slug variables
        uses: rlespinasse/github-slug-action@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Steup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn ipfs-build
      - name: Deploy to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{secrets.WEB3_STORAGE_TOKEN}}
          path_to_add: 'build'
